env:
  browser: true
  es2021: true
extends:
  - prettier
  - standard-with-typescript
  - plugin:react/recommended
parserOptions:
  "project": "./tsconfig.json"
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules: {
  "react/react-in-jsx-scope": "off",
  "react/jsx-uses-react": "off",
  "prettier/prettier": "error",
  "@typescript-eslint/semi": "off",
  "@typescript-eslint/member-delimiter-style": "off",
  "@typescript-eslint/space-before-function-paren": "off"
}
