version: '3.9'
services:

  postgres:
    image: "postgres:15.3"
    volumes:
    - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

  fa-minio:
    container_name: fa-minio
    image: "minio/minio:RELEASE.2023-02-17T17-52-43Z"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./volumes/regula/minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /export --address ':9000' --console-address ':9001'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./volumes/elastic-data:/data
    ports:
      - "9200:9200"
      - "9300:9300"