ALTER TABLE users
    ADD COLUMN password TEXT;

CREATE TABLE email_registration_confirmations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT 50) PRIMARY KEY,
    email         TEXT      NOT NULL,
    code          TEXT      NOT NULL,
    creation_time TIMESTAMP NOT NULL
)