name: Build and push image to ECR
on:
  push:
    branches:
      - aws
  workflow_dispatch:
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [ 'frontend', 'backend' ] }
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Copy file
        run: |
          cp backend/core/api/src/core.openapi.yaml frontend/core.openapi.yaml
        if: ${{ matrix.dir == 'frontend' }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./git_update.sh -v major

      - name: Build, Tag, and Push the Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: test-app
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        working-directory: ${{ matrix.dir }}