name: Backend CI/CD. Build, Push to GHCR and deploy
on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
jobs:
  build-and-push:
    name: Build, Push to GHCR and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "Environment input: ${{ github.event.inputs.environment }}"
          echo "Event name: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "push" ]]; then
            ENVIRONMENT="dev"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENVIRONMENT="${{ github.event.inputs.environment }}"
          fi
          
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          
          if [[ ! "$ENVIRONMENT" =~ ^(dev|prod)$ ]]; then
            echo "Environment: $ENVIRONMENT"
            echo "Error: Invalid environment. Must be 'dev' or 'prod'."
            exit 1
          fi

          if [[ "$ENVIRONMENT" == "dev" ]]; then
            echo "SERVER=app.dev.firstapproval.io" >> $GITHUB_ENV
          else
            echo "SERVER=firstapproval.io" >> $GITHUB_ENV
          fi

      - name: Show environment value
        run: |
          echo "The environment is: ${{ env.ENVIRONMENT }}"
          echo "The server is: $SERVER"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          echo "The environment is: $ENVIRONMENT"
    
          if [[ ${{ env.ENVIRONMENT }} == "prod" ]]; then
            IMAGE_TAG="ghcr.io/firstapproval/fa-mono-backend-prod"
          else
            IMAGE_TAG="ghcr.io/firstapproval/fa-mono-backend"
          fi
          echo "The image tag is: $IMAGE_TAG"
          docker buildx build \
            --build-arg ENVIRONMENT=$ENVIRONMENT \
            --platform linux/amd64 \
            -f Dockerfile-github \
            -t $IMAGE_TAG . && docker push $IMAGE_TAG
        working-directory: backend

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh

          if [[ "${{ env.ENVIRONMENT }}" == "prod" ]]; then
            echo "${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          else
            echo "${{ secrets.DEV_SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          fi

          chmod 600 ~/.ssh/id_rsa
          ssh-agent bash -c 'echo "SSH agent started" && ssh-add ~/.ssh/id_rsa'
          ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts  

      - name: Pull image
        run: |
          echo "Pulling the backend image..."
          ssh ubuntu@$SERVER "docker compose pull backend"

      - name: Deploy image
        run: |
          echo "Deploying the backend image..."
          ssh ubuntu@$SERVER "docker compose up -d backend --force-recreate"

      - name: Verify backend startup after deployment
        run: |
          ssh ubuntu@$SERVER "timeout 30s docker compose logs backend -f | grep -q 'Started FirstApprovalApplicationKt'"
